### ISSUE TITLE
Fix RuntimeException: A broker is already registered on the path /brokers/ids/1001 when container is restarted

### ISSUE THREAD

**Issue by jeqo** [jeqo/docker-image-apache-kafka#1]
```
kafka_1      | [2017-01-12 07:16:39,000] INFO Result of znode creation is: NODEEXISTS (kafka.utils.ZKCheckedEphemeral)
kafka_1      | [2017-01-12 07:16:39,001] FATAL [Kafka Server 1001], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1      | java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1001. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
kafka_1      | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:393)
kafka_1      | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:379)
kafka_1      | 	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:70)
kafka_1      | 	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:51)
kafka_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:270)
kafka_1      | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
kafka_1      | 	at kafka.Kafka$.main(Kafka.scala:67)
kafka_1      | 	at kafka.Kafka.main(Kafka.scala)

```

**Comment by jeqo** [comment]
This happens when `kafka` container is killed instead of stopped. After stopping `kafka` containers, it disconnects from `zookeeper` and starts later without this exception.

**Comment by HappiLamb** [comment]
How can I resolve this issue?

**Comment by jeqo** [comment]
@BeScrumpy this happens when you kill your kafka process or it crashs, and it does not close its zookeeper connection correctly. 
You can try to start your kafka process again, or stop it correctly to avoid this to happen.
Hope this helps.

**Comment by ayiis** [comment]
I do "stop" before "start" it, not sure about the side-effect, but it worked.
like this:
```bash
#!/bin/bash
#chkconfig:- 85 15

case $1 in
	start)
		/usr/kafka/kafka-0.10.0.0/bin/kafka-server-stop.sh /usr/kafka/kafka-0.10.0.0/config/server.properties
		/usr/kafka/kafka-0.10.0.0/bin/kafka-server-start.sh -daemon /usr/kafka/kafka-0.10.0.0/config/server.properties
		;;
	stop)
		/usr/kafka/kafka-0.10.0.0/bin/kafka-server-stop.sh /usr/kafka/kafka-0.10.0.0/config/server.properties
		;;
	*)
		echo "start|stop"
		;;
esac
exit 0


```

**Comment by timbarrass** [comment]
Sorry for the thread necromancy but if this *does* happen what's the mechanism for recovery -- is it possible to tell zookeeper that the existing node state should be disregarded, for example?
